##What is Numpy?


*   The numerical python library used for working with arrays.
*   Created in 2005 by Travis Oliphant
*   Written partially in Python, but most of the parts that require fast computation are written in C or C++.





. 






##Why use Numpy?
*   Has functions for working in domain of linear algebra, fourier transform, and matrices.
*   Aims to provide an array object that is up to 50x times faster than traditional Python lists.
*   Forms the foundation of Machine Learning Stack


### Import Numpy
Numpy package is imported as alias **np**

In [1]:
import numpy as np
# The list type data type which we work with in numpy is called n-dim array. 

## Creating an 1-D Array(Vector)


In [2]:
# There are many ways to create a Vector. The first one is with use of python list.

#Row Vector
a = [2,6,4,8,2,1,4,3]
arr = np.array(a)
print(arr)
print('Shape of Matrix is',arr.shape)

[2 6 4 8 2 1 4 3]
Shape of Matrix is (8,)


## Creating a 2D array (Matrix)

In [17]:

# Similiarly, Matrix is formed using list of list.
list_mat = [[2,6,4],[8,2,1],[1,4,3]] 

array_mat = np.array(list_mat)

print(array_mat)

[[2 6 4]
 [8 2 1]
 [1 4 3]]


In [12]:
# Printing type of arr object
print("Array is of type: ", type(array_mat))
 

Array is of type:  <class 'numpy.ndarray'>


In [13]:
# Printing array dimensions (axes)
print("No. of dimensions: ", array_mat.ndim)

No. of dimensions:  2


In [14]:
# Printing shape of array
print("Shape of array: ", array_mat.shape)
 

Shape of array:  (3, 3)


In [15]:
# Printing size (total number of elements) of array
print("Size of array: ", array_mat.size)

Size of array:  9


In [16]:
#Printing type of elements in array
print("Array stores elements of type: ", array_mat.dtype)

Array stores elements of type:  int32


**The elements of an array are originally unknown, but it's size is known. Hence, Numpy offers several functions to create arrays with initial placeholder content.**

In [18]:


#returns a new array of specified size filled with zeros
x_zeros = np.zeros((2, 2))

print (x_zeros)


[[0. 0.]
 [0. 0.]]


In [19]:


#returns a new array of specified size filled with ones
x_ones = np.ones((2, 2))

print (x_ones)


[[1. 1.]
 [1. 1.]]


In [8]:


#returns a new array of specified size filled with random values
x_default = np.empty((2, 3))

print (x_default)

[[0. 0. 0.]
 [0. 0. 0.]]


**Here we will see how to create an array from numerical ranges**

In [21]:
x = np.arange(5)
print (x)


[0 1 2 3 4]


In [22]:
# start and stop parameters set
import numpy as np
x = np.arange(10,20,2)
print (x)


[10 12 14 16 18]


In [23]:
import numpy as np

x = np.linspace(0, 2, 9)

print(x)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


#### Array Indexing
Knowing the basics of array indexing is important for analysing and manipulating the array object.
* Slicing
* Integer array indexing
* Boolean array indexing

In [24]:
#Here we will discuss only slicing
x = np.arange(10, 28, 2).reshape(3,3)

print(x)


[[10 12 14]
 [16 18 20]
 [22 24 26]]


In [29]:
#We will the perform slicing on the given array now

y = x[:, 2]

print(y)


[14 20 26]


In [28]:
y = x[2, :]

print(y)


[22 24 26]


In [32]:
#Reshaping

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
x  = np.arange(120, 138, 2)
print(x)


[120 122 124 126 128 130 132 134 136]


In [34]:
y = x.reshape(3, 3)
print('Reshaped the matrix into a 3*3 matrix: ')
print(y)

Reshaped the matrix into a 3*3 matrix: 
[[120 122 124]
 [126 128 130]
 [132 134 136]]


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [6]:
standard_deviation = np.std(arr)
print(standard_deviation)

3.452052529534663


In [7]:
#mean
print(np.mean(arr))

6.5
